<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PedidosPendientes.Core\PedidosPendientes.Core.csproj" />
    <ProjectReference Include="..\PedidosPendientes.Infrastructure\PedidosPendientes.Infrastructure.csproj" />
  </ItemGroup>

</Project>
