// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosPendientes.Infrastructure.Data;

#nullable disable

namespace PedidosPendientes.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707072552_MejorasOperativas")]
    partial class MejorasOperativas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PedidosPendientes.Core.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.CriticidadUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_CriticidadUbicaciones_Tipo_Codigo");

                    b.ToTable("CriticidadUbicaciones", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoCompras")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProveedorEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoCompras")
                        .HasDatabaseName("IX_EmailLogs_Documento");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_EmailLogs_SentAt");

                    b.ToTable("EmailLogs", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.MaterialClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Material")
                        .IsUnique()
                        .HasDatabaseName("UQ_MaterialClasificaciones_Material");

                    b.ToTable("MaterialClasificaciones", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("AnuladoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("CantidadRecibida")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CentroCoste")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentoCompras")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EnFalta")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("EnFaltaAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExpedienteAdministrativo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly>("FechaDocumento")
                        .HasColumnType("date");

                    b.Property<string>("Incidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUploadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumMaterialProveedor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("PausaReclamacion")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PorEntregarCantidad")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ProveedorCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProveedorNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Recibido")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("RecibidoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Reclamado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReclamadoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReclamadoCount")
                        .HasColumnType("int");

                    b.Property<string>("ReferenciaProveedor")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TextoBreve")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TieneHistorialEntrega")
                        .HasColumnType("bit");

                    b.Property<string>("TipoImputacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Anulado")
                        .HasDatabaseName("IX_Orders_Anulado");

                    b.HasIndex("FechaDocumento")
                        .HasDatabaseName("IX_Orders_FechaDocumento");

                    b.HasIndex("ProveedorCodigo")
                        .HasDatabaseName("IX_Orders_ProveedorCodigo");

                    b.HasIndex("ProveedorNombre")
                        .HasDatabaseName("IX_Orders_ProveedorNombre");

                    b.HasIndex("DocumentoCompras", "Material")
                        .IsUnique()
                        .HasDatabaseName("UQ_Orders_Documento_Material");

                    b.HasIndex("Recibido", "TieneHistorialEntrega", "Anulado")
                        .HasDatabaseName("IX_Orders_Estado");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AcuerdoMarco")
                        .HasColumnType("bit");

                    b.Property<string>("Centro")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NifCif")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NotasPenalizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlazoEntregaDias")
                        .HasColumnType("int");

                    b.Property<string>("Poblacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proveedores_Codigo");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Proveedores_Nombre");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.ProviderResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentoCompras")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly?>("FechaEstimada")
                        .HasColumnType("date");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Material")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("ProveedorNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ProviderResponses_CreatedAt");

                    b.HasIndex("DocumentoCompras")
                        .HasDatabaseName("IX_ProviderResponses_Documento");

                    b.HasIndex("RevisionEstado")
                        .HasDatabaseName("IX_ProviderResponses_Revision");

                    b.ToTable("ProviderResponses", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.StockMd04Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CargadoAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ConsumoMedio")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("PuntoPedido")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Semaforo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Stock")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TextoBreve")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Material")
                        .HasDatabaseName("IX_StockMd04_Material");

                    b.HasIndex("Semaforo")
                        .HasDatabaseName("IX_StockMd04_Semaforo");

                    b.ToTable("StockMd04", (string)null);
                });

            modelBuilder.Entity("PedidosPendientes.Core.Entities.UploadLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Actualizados")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Filas")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Insertados")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "At")
                        .HasDatabaseName("IX_UploadLogs_Tipo_At");

                    b.ToTable("UploadLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
